In [1]:
import numpy as np

In [2]:
vowels=np.array(['a','e','i','o','u'])

In [3]:
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [6]:
names = ['jason','syed']

In [35]:
#This will evaluate multiple names, but only one character at a time
BF= np.array(np.char.endswith(names, 'n'), dtype=int)

In [29]:
BF

array([1, 0])

In [25]:
lastchar = [x[-1] for x in names]

In [26]:
np.isin(lastchar,vowels)

array([False, False])

In [27]:
#do a postivie test make sure eval is working

In [30]:
otherletters = np.array(['n','z','g'])

In [31]:
np.isin(lastchar,otherletters)

array([ True, False])